### ISSUE TITLE
Bad CSS included in upgrade step change

### ISSUE THREAD

**Issue by smcmahon** [collective/webcouturier.dropdownmenu#12]
commit 8a3568cb11829eb021bbba73f1dd444457f626ff which adds an upgrade step also makes some ill-advised CSS changes. Some are flatly bad CSS (color: 123456;;), others apply colors and changes that may have been desired by the author for a particular site, but will be unwanted by most users.
I suggest the CSS changes from this commit be reverted.

**Comment by agitator** [comment]
fixed with https://github.com/collective/webcouturier.dropdownmenu/commit/748c5590cd2eb8696a975c0b547391b4f616b68b
