### ISSUE TITLE
Disable clicking menu items that have children doesn't work

### ISSUE THREAD

**Issue by hvelarde** [collective/webcouturier.dropdownmenu#15]
All items on menu are clickable, even if you disable the **Enable clicking menu items that have children** option.

**Comment by rodfersou** [comment]
@hvelarde I don't remember why we need this.. can you help me?

**Comment by hvelarde** [comment]
this is a requirement for Portal Brasil 2016; on hold.

**Comment by mauritsvanrees** [comment]
For the record, I am using this in a Plone 4.3 (formerly 4.2) site and it is working there. IIRC this is the site that I wrote this feature for. :-)
BTW, the site is http://www.mpi.nl.

**Comment by hvelarde** [comment]
closing it then; maybe is an issue with the Diazo theme.
