### ISSUE TITLE
Add class for elements that have subitems

### ISSUE THREAD

**Issue by toutpt** [collective/webcouturier.dropdownmenu#2]
@TheoFromSed :

Hi Denis.

At this moment I can't determine that one element have subitem while other don't have it. I think adding class 'havesubitems' will make your product more flexible. For example, there will be able to add arrow image to elements that have submenu.

<ul id="portal-globalnav">
<li id="portaltab-1">
<a href="...">Link</a>
</li>
<li id="portaltab-2" class="havesubmenu">
<a href="...">Link</a>
<ul class="submenu">
<li><a href="...">Link</a></li>
<li class="havesubmenu"><a href="...">Link</a>
<ul>...</ul>

</li>

Thank you.

**Comment by agitator** [comment]
@toutpt there is a hasDropDown and dropdown-submenu as class, anything else you were looking for?
