### ISSUE TITLE
Fix/implement responsive (mobile) navigation for sublevels

### ISSUE THREAD

**Issue by agitator** [collective/webcouturier.dropdownmenu#30]
expand of sublevels doesn't work

http://slicknav.com/ looks like a possible solution

**Comment by agitator** [comment]
or http://mmenu.frebsite.nl

**Comment by jensens** [comment]
Confirmed, expansion of third levels are not working with mobile menu.

**Comment by agitator** [comment]
fixed with https://github.com/collective/webcouturier.dropdownmenu/pull/35
