### ISSUE TITLE
Classes duplication for first-level elements

### ISSUE THREAD

**Issue by gvizdyk** [collective/webcouturier.dropdownmenu#31]
If "Home" tab is switched off, we get a problem with the definition of classes, such as: two elements of one level receive the same "selected active" class. 

![bug_webcouturier_dropdownmenu](https://cloud.githubusercontent.com/assets/1560748/24353284/95a47abe-12f5-11e7-8e0f-a4a1f150478c.png)

This is connected with a bad definition of the condition for [classes assignment](
https://github.com/collective/webcouturier.dropdownmenu/blob/master/src/webcouturier/dropdownmenu/browser/dropdown_recurse.pt#L26):

```python
class_selected  python:' selected active' if item_url in context.absolute_url() else '';
```

**Comment by michaeldunstan** [comment]
Looks like the problem was introduced in 938c36fae58f15af34c44d2c037b7ba2d1972711

I don't think dropdown_sections.pt needed to be updated in that patch.
