### ISSUE TITLE
Dropdown menu style

### ISSUE THREAD

**Issue by LFPSGS** [collective/webcouturier.dropdownmenu#39]
Hi! I'm customizing a theme (plone's default theme - Barceloneta) and despite my efforts I can't seem to find which variables this addon is using, so I can change BG colors and font styles as well.

I already changed everything else I need in Barceloneta theme.

I tried to change the dropdown.less and recompile it with dropdownmenu-compiled.css name that I found in the directory :

`/etc/plone/buildout-cache/eggs/webcouturier.dropdownmenu-3.0.2-py2.7.egg/webcouturier/dropdownmenu/browser/static`

But no luck so far. Can you guys help me?

Best regards,

**Comment by agitator** [comment]
The easiest way is to override the styles in your own custom theme, which can be a copy of barceloneta (you're not changing the files within the eggs directory? changes will most probably be gone with an update...).

https://pypi.python.org/pypi/bobtemplates.plone allows you to create your own theme package

**Comment by LFPSGS** [comment]
Thanks for the heads up @agitator. I've tried every variable I found in Barceloneta to override but none seems to change this particular dropdown addon menu.

That's why I thought that I needed to rebuild the dropdown's menu css inside the eggs directory (which doesn't work btw).

Do you know which variable affects font and bg color btw? I copied Barceloneta and customized the styless.less then rebuild it to create a styless.css. That's where I'm writting all my customizations. 

I'm far from a programmer/designer so Iam adventuring through plone/css customization for minor enhancements. ^^

Best regards,

**Comment by agitator** [comment]
Just copy over the dropdown.less into your theme and make sure you add it in your .../theme/less/barceloneta.plone.less so that it get's read to compile (it will then pick up your variables)

**Comment by LFPSGS** [comment]
@agitator Thank you mate! That did the trick! awsome to talk to someone who helps :-D

**Comment by agitator** [comment]
@LFPSGS nice, you're welcome ;-)
