### ISSUE TITLE
Menu item reorder and filtering patch

### ISSUE THREAD

**Issue by miohtama** [collective/webcouturier.dropdownmenu#8]
I have created a patch which adds support for per-folder menu item filtering and reordering. This allows you fine-tune your dropdown menu content to differ from the actual sitemap. For example, in some cases you want less items appear in the menu than in the sitemap.

This happens by having new Action menu item "Dropdown menu settings" on folders. There you have a z3c.form which allows you select and reorder content items.

The (unfinished) code is here: https://github.com/miohtama/webcouturier.dropdownmenu

Before proceeding with unit testing and documention I'd like to know which is BBB policy of webcouturier.dropdownmenu.

- Code is Plone 4.0+ / Python 2.6 only, though it can be modified to just not have the new functionality on older Plone versions

- The form machinery uses plone.form.directives which depends on five.grok which some people don't like. However this makes form code very compact and easy to maintain and doing it with barebone z3c.form / ZCML would double the number of code lines

So the questions

- Is plone.form.directives ok dependency 

- Is Plone 4+ ok target or must the backwards compatiblity to Plone 3 retained with new releases

**Comment by jensens** [comment]
I'd say this one is outdated.
