### ISSUE TITLE
Content type icons missing

### ISSUE THREAD

**Issue by mhallika** [collective/webcouturier.dropdownmenu#9]
I am upgrading to Plone 4.2 from 3.x.x where I used w.dropdownmenu. On 4.x version plones, the content type icons are missing, unless there is MIME type associated. 
pdf, MS word, etc icons are visible, but collections, links and folders are missing. I think Plone 4.x versions are handling icons a bit diffrently than before and it breaks w. dropdownmenu.

**Comment by jensens** [comment]
invalid
